/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Datos.AlquilerStore;
import Datos.InquilinoStore;
import Datos.ViviendaStore;
import Logica.Alquileres;
import Logica.Inquilino;
import Logica.Vivienda;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Ventana para registrar un alquiler nuevo o para editar uno
 * que ya existe en el ArrayList de alquileres.
 *
 * El inquilino y la vivienda se guardan como objetos, por eso
 * los dos deben existir antes de crear el contrato.
 *
 * @author mauri
 */
public class DlgNuevoAlquiler extends javax.swing.JDialog {

    /**
     * Alquiler que se está editando.
     * Si vale null quiere decir que se está registrando uno nuevo.
     */
    private Alquileres alquilerEditar = null;

    /**
     * Creates new form DlgNuevoAlquiler
     */
    public DlgNuevoAlquiler(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();

        cargarInquilinos();
        cargarViviendas(null);
        cargarEstados();

        // El número de alquiler es consecutivo
        txtnumAlquiler.setText(
                String.valueOf(AlquilerStore.generarNumeroAlquiler()));

        datePicker1.setDate(LocalDate.now());
    }

    /**
     * Llena el combo con los inquilinos registrados.
     */
    private void cargarInquilinos() {

        cmbInquilino.removeAllItems();
        cmbInquilino.addItem("Seleccione Inquilino...");

        ArrayList<Inquilino> lista =
                InquilinoStore.getListaInquilinos();

        for (int i = 0; i < lista.size(); i++) {

            Inquilino inquilino = lista.get(i);

            cmbInquilino.addItem(inquilino.getCedInqui()
                    + " - " + inquilino.getNomInqui());
        }
    }

    /**
     * Llena el combo con las viviendas disponibles.
     *
     * Cuando se está editando también se agrega la vivienda que ya
     * tiene el contrato, porque esa aparece como alquilada.
     */
    private void cargarViviendas(Vivienda viviendaActual) {

        jComboBox1.removeAllItems();
        jComboBox1.addItem("Seleccione Vivienda Disponible...");

        ArrayList<Vivienda> disponibles =
                ViviendaStore.obtenerDisponibles();

        for (int i = 0; i < disponibles.size(); i++) {

            Vivienda vivienda = disponibles.get(i);

            jComboBox1.addItem(vivienda.getIdVivienda()
                    + " - " + vivienda.getDescripcion());
        }

        if (viviendaActual != null
                && !"Disponible".equalsIgnoreCase(
                        viviendaActual.getEstado())) {

            jComboBox1.addItem(viviendaActual.getIdVivienda()
                    + " - " + viviendaActual.getDescripcion());
        }
    }

    /**
     * Llena el combo con los estados que puede tener un contrato.
     */
    private void cargarEstados() {

        cmbEstado.removeAllItems();
        cmbEstado.addItem("Seleccione el Estado...");
        cmbEstado.addItem("Vigente");
        cmbEstado.addItem("Vencido");
        cmbEstado.addItem("Cancelado");
    }

    /**
     * Carga en pantalla los datos de un alquiler para editarlo.
     */
    public void cargarAlquiler(Alquileres alquiler) {

        this.alquilerEditar = alquiler;

        txtnumAlquiler.setText(String.valueOf(alquiler.getNumAlquiler()));
        datePicker1.setDate(alquiler.getFechContrato());
        txtcantMeses.setText(String.valueOf(alquiler.getCantMeses()));
        txtMetConstruccion.setText(String.valueOf(alquiler.getNumAdultos()));
        txtcantNiños.setText(String.valueOf(alquiler.getNumNinos()));
        txtDepositoGaran.setText(
                String.valueOf(alquiler.getDepositoGarantia()));
        txtPrecioAlquilerMen.setText(
                String.valueOf(alquiler.getPrecioAlquiler()));
        txtPorcentajeIncrementoAnual.setText(
                String.valueOf(alquiler.getPorcIncremAnual()));

        if (alquiler.getInquilino() != null) {

            cmbInquilino.setSelectedItem(
                    alquiler.getInquilino().getCedInqui()
                    + " - " + alquiler.getInquilino().getNomInqui());
        }

        cargarViviendas(alquiler.getVivienda());

        if (alquiler.getVivienda() != null) {

            jComboBox1.setSelectedItem(
                    alquiler.getVivienda().getIdVivienda()
                    + " - " + alquiler.getVivienda().getDescripcion());
        }

        cmbEstado.setSelectedItem(alquiler.getEstado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnumAlquiler = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPorcentajeIncrementoAnual = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcantMeses = new javax.swing.JTextField();
        txtMetConstruccion = new javax.swing.JTextField();
        txtcantNiños = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrecioAlquilerMen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbInquilino = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txtDepositoGaran = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setText("Registro del Nuevo Alquiler");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Complete la Información del Alquiler");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alquiler(2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Alquiler", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Número del Alquiler:");

        txtnumAlquiler.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha del Contrato:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad de Meses:");

        jLabel4.setText("Número de niños:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Deposito de Garantia:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Porcentaje de Incremento Anual:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar(2).png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad de Adultos:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Inquilino:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Precio de Alquiler Mensual:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vivienda:");

        cmbInquilino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Inquilino..." }));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Estado..." }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Vivienda Disponible..." }));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CasaReistrada.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 223, Short.MAX_VALUE)
                                    .addComponent(cmbInquilino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPorcentajeIncrementoAnual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(txtPrecioAlquilerMen, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDepositoGaran, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcantNiños, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMetConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtcantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMetConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcantNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDepositoGaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPrecioAlquilerMen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPorcentajeIncrementoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (!validarCampos()) {
            return;
        }

        Inquilino inquilino = obtenerInquilinoSeleccionado();

        if (inquilino == null) {
            JOptionPane.showMessageDialog(this,
                    "El inquilino seleccionado no existe en el sistema.");
            return;
        }

        Vivienda vivienda = obtenerViviendaSeleccionada();

        if (vivienda == null) {
            JOptionPane.showMessageDialog(this,
                    "La vivienda seleccionada no existe en el sistema.");
            return;
        }

        int numero = Integer.parseInt(txtnumAlquiler.getText().trim());
        LocalDate fecha = datePicker1.getDate();
        int meses = Integer.parseInt(txtcantMeses.getText().trim());
        int adultos = Integer.parseInt(
                txtMetConstruccion.getText().trim());
        int ninos = Integer.parseInt(txtcantNiños.getText().trim());
        double deposito = Double.parseDouble(
                txtDepositoGaran.getText().trim().replace(",", "."));
        double precio = Double.parseDouble(
                txtPrecioAlquilerMen.getText().trim().replace(",", "."));
        double porcentaje = Double.parseDouble(
                txtPorcentajeIncrementoAnual.getText().trim()
                        .replace(",", "."));
        String estado = cmbEstado.getSelectedItem().toString();

        if (alquilerEditar == null) {

            // Registro nuevo
            if (!"Disponible".equalsIgnoreCase(vivienda.getEstado())) {

                JOptionPane.showMessageDialog(this,
                        "La vivienda no está disponible para alquilar.");
                return;
            }

            Alquileres nuevo = new Alquileres(
                    numero, fecha, meses, adultos, ninos,
                    deposito, precio, porcentaje,
                    inquilino, vivienda, estado);

            if (AlquilerStore.insertar(nuevo)) {

                JOptionPane.showMessageDialog(this,
                        "Alquiler registrado correctamente.");
                dispose();

            } else {

                JOptionPane.showMessageDialog(this,
                        "No se pudo registrar el alquiler.\n"
                        + "Revise que el número no esté repetido y "
                        + "que la vivienda esté disponible.");
            }

        } else {

            // Modificación de un alquiler existente
            int indice = AlquilerStore.buscarIndice(
                    alquilerEditar.getNumAlquiler());

            Alquileres modificado = new Alquileres(
                    numero, fecha, meses, adultos, ninos,
                    deposito, precio, porcentaje,
                    inquilino, vivienda, estado);

            if (AlquilerStore.modificar(indice, modificado)) {

                JOptionPane.showMessageDialog(this,
                        "Alquiler modificado correctamente.");
                dispose();

            } else {

                JOptionPane.showMessageDialog(this,
                        "No se pudo modificar el alquiler.\n"
                        + "Revise que el número no esté repetido.");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Busca en el ArrayList el inquilino elegido en el combo.
     */
    private Inquilino obtenerInquilinoSeleccionado() {

        String seleccion = cmbInquilino.getSelectedItem().toString();

        int posicionGuion = seleccion.indexOf(" - ");

        if (posicionGuion == -1) {
            return null;
        }

        try {

            int cedula = Integer.parseInt(
                    seleccion.substring(0, posicionGuion).trim());

            return InquilinoStore.buscarPorCedula(cedula);

        } catch (NumberFormatException error) {
            return null;
        }
    }

    /**
     * Busca en el ArrayList la vivienda elegida en el combo.
     */
    private Vivienda obtenerViviendaSeleccionada() {

        String seleccion = jComboBox1.getSelectedItem().toString();

        int posicionGuion = seleccion.indexOf(" - ");

        if (posicionGuion == -1) {
            return null;
        }

        try {

            int id = Integer.parseInt(
                    seleccion.substring(0, posicionGuion).trim());

            return ViviendaStore.buscarPorId(id);

        } catch (NumberFormatException error) {
            return null;
        }
    }

    /**
     * Revisa que todos los datos digitados sean correctos.
     *
     * @return true si todo está bien, false si hay algún error
     */
    private boolean validarCampos() {

        String numero = txtnumAlquiler.getText().trim();

        if (numero.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Debe digitar el número del alquiler.");
            txtnumAlquiler.requestFocus();
            return false;
        }

        try {

            if (Integer.parseInt(numero) <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El número del alquiler debe ser mayor que cero.");
                return false;
            }

        } catch (NumberFormatException error) {

            JOptionPane.showMessageDialog(this,
                    "El número del alquiler solo puede tener números.");
            return false;
        }

        if (datePicker1.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar la fecha del contrato.");
            return false;
        }

        if (!enteroValido(txtcantMeses.getText(),
                "la cantidad de meses", 1)) {
            return false;
        }

        if (!enteroValido(txtMetConstruccion.getText(),
                "la cantidad de adultos", 1)) {
            return false;
        }

        if (!enteroValido(txtcantNiños.getText(),
                "la cantidad de niños", 0)) {
            return false;
        }

        if (!decimalValido(txtDepositoGaran.getText(),
                "el depósito de garantía", 0)) {
            return false;
        }

        if (!decimalValido(txtPrecioAlquilerMen.getText(),
                "el precio del alquiler", 1)) {
            return false;
        }

        String porcentaje = txtPorcentajeIncrementoAnual.getText()
                .trim().replace(",", ".");

        if (porcentaje.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Debe digitar el porcentaje de incremento anual.");
            return false;
        }

        try {

            double valor = Double.parseDouble(porcentaje);

            if (valor < 1 || valor > 30) {
                JOptionPane.showMessageDialog(this,
                        "El porcentaje de incremento debe estar "
                        + "entre 1 y 30.");
                return false;
            }

        } catch (NumberFormatException error) {

            JOptionPane.showMessageDialog(this,
                    "El porcentaje de incremento debe ser un número.");
            return false;
        }

        if (cmbInquilino.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar el inquilino.\n"
                    + "Si no aparece, regístrelo primero.");
            return false;
        }

        if (jComboBox1.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar la vivienda.\n"
                    + "Solo aparecen las viviendas disponibles.");
            return false;
        }

        if (cmbEstado.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar el estado del contrato.");
            return false;
        }

        return true;
    }

    /**
     * Revisa que el texto sea un número entero mayor o igual al mínimo.
     */
    private boolean enteroValido(String texto, String nombreCampo,
            int minimo) {

        String valor = texto.trim();

        if (valor.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Debe digitar " + nombreCampo + ".");
            return false;
        }

        try {

            int numero = Integer.parseInt(valor);

            if (numero < minimo) {
                JOptionPane.showMessageDialog(this,
                        "El valor de " + nombreCampo
                        + " no puede ser menor que " + minimo + ".");
                return false;
            }

        } catch (NumberFormatException error) {

            JOptionPane.showMessageDialog(this,
                    "El valor de " + nombreCampo
                    + " debe ser un número entero.");
            return false;
        }

        return true;
    }

    /**
     * Revisa que el texto sea un número mayor o igual al mínimo
     * (puede llevar decimales).
     */
    private boolean decimalValido(String texto, String nombreCampo,
            double minimo) {

        String valor = texto.trim().replace(",", ".");

        if (valor.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Debe digitar " + nombreCampo + ".");
            return false;
        }

        try {

            double numero = Double.parseDouble(valor);

            if (numero < minimo) {
                JOptionPane.showMessageDialog(this,
                        "El valor de " + nombreCampo
                        + " no puede ser menor que " + minimo + ".");
                return false;
            }

        } catch (NumberFormatException error) {

            JOptionPane.showMessageDialog(this,
                    "El valor de " + nombreCampo + " debe ser un número.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgNuevoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgNuevoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgNuevoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgNuevoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgNuevoAlquiler dialog = new DlgNuevoAlquiler(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbInquilino;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDepositoGaran;
    private javax.swing.JTextField txtMetConstruccion;
    private javax.swing.JTextField txtPorcentajeIncrementoAnual;
    private javax.swing.JTextField txtPrecioAlquilerMen;
    private javax.swing.JTextField txtcantMeses;
    private javax.swing.JTextField txtcantNiños;
    private javax.swing.JTextField txtnumAlquiler;
    // End of variables declaration//GEN-END:variables
}
