/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author mauri
 */
public class FrmSistemaGuanaRent extends javax.swing.JFrame {

    /**
     * Creates new form FrmSistemaGuanaRent
     */
    public FrmSistemaGuanaRent() {

        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de Alquileres GuanaRent");

        java.net.URL rutaImagen
                = getClass().getResource("/imagenes/alquiler.jpg");

        if (rutaImagen != null) {

            ImageIcon imagen = new ImageIcon(rutaImagen);

            Image img = imagen.getImage().getScaledInstance(
                    lblImagen.getWidth(),
                    lblImagen.getHeight(),
                    Image.SCALE_SMOOTH
            );

            lblImagen.setIcon(new ImageIcon(img));

        } else {
            System.out.println(
                    "No se encontró la imagen alquiler.jpg"
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnPropietarios = new javax.swing.JButton();
        btnViviendas = new javax.swing.JButton();
        btnInquilinos = new javax.swing.JButton();
        btnAlquileres = new javax.swing.JButton();
        btnMensualidades = new javax.swing.JButton();
        btnGanancias = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        menuRegistros = new javax.swing.JMenu();
        mnuPropietarios = new javax.swing.JMenuItem();
        mnuInquilinos = new javax.swing.JMenuItem();
        mnuViviendas = new javax.swing.JMenuItem();
        mnuAlquileres = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        mnuMensualidades = new javax.swing.JMenuItem();
        mnuGanancias = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GuanaRent");

        pnlMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/propietario.png"))); // NOI18N
        btnPropietarios.setText("Propietarios");
        btnPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietariosActionPerformed(evt);
            }
        });

        btnViviendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vivienda.png"))); // NOI18N
        btnViviendas.setText("Viviendas");
        btnViviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViviendasActionPerformed(evt);
            }
        });

        btnInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inquilino.png"))); // NOI18N
        btnInquilinos.setText("Inquilinos");
        btnInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInquilinosActionPerformed(evt);
            }
        });

        btnAlquileres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alquileres.png"))); // NOI18N
        btnAlquileres.setText("Alquileres");
        btnAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquileresActionPerformed(evt);
            }
        });

        btnMensualidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mesnsualidad.png"))); // NOI18N
        btnMensualidades.setText("Mensualidades");
        btnMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualidadesActionPerformed(evt);
            }
        });

        btnGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ganancias.png"))); // NOI18N
        btnGanancias.setText("Ganancias");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViviendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInquilinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlquileres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMensualidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMensualidades, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alquiler.jpg"))); // NOI18N

        menuArchivo.setText("Archivo");

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirmenuu.png"))); // NOI18N
        mnuSalir.setText("Salir");
        menuArchivo.add(mnuSalir);

        jMenuBar1.add(menuArchivo);

        menuRegistros.setText("Registros");

        mnuPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/propietarios.menu.png"))); // NOI18N
        mnuPropietarios.setText("Propietarios");
        menuRegistros.add(mnuPropietarios);

        mnuInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inquilinosmenuu.png"))); // NOI18N
        mnuInquilinos.setText("Inquilinos");
        menuRegistros.add(mnuInquilinos);

        mnuViviendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/viviendasmenuu.png"))); // NOI18N
        mnuViviendas.setText("Viviendas");
        menuRegistros.add(mnuViviendas);

        mnuAlquileres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alquileresmenuu.png"))); // NOI18N
        mnuAlquileres.setText("Alquileres");
        menuRegistros.add(mnuAlquileres);

        jMenuBar1.add(menuRegistros);

        menuProcesos.setText("Procesos");

        mnuMensualidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mensualidadesmenuu.png"))); // NOI18N
        mnuMensualidades.setText("Mensualidades");
        menuProcesos.add(mnuMensualidades);

        mnuGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gananciasmenuu.png"))); // NOI18N
        mnuGanancias.setText("Ganancias");
        menuProcesos.add(mnuGanancias);

        jMenuBar1.add(menuProcesos);

        menuAyuda.setText("Ayuda");

        mnuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acercademenuu.png"))); // NOI18N
        mnuAcercaDe.setText("Acerca de");
        menuAyuda.add(mnuAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietariosActionPerformed
        DlgPropietarios ventana = new DlgPropietarios(this, true);

        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnPropietariosActionPerformed

    private void btnInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInquilinosActionPerformed
        DlgInquilinos ventana = new DlgInquilinos(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnInquilinosActionPerformed

    private void btnViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendasActionPerformed
        DlgViviendas ventana = new DlgViviendas(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnViviendasActionPerformed

    private void btnAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquileresActionPerformed
        DlgAlquileres ventana = new DlgAlquileres(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAlquileresActionPerformed

    private void btnMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualidadesActionPerformed
        FrmMensualidades ventana = new FrmMensualidades();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMensualidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistemaGuanaRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquileres;
    private javax.swing.JButton btnGanancias;
    private javax.swing.JButton btnInquilinos;
    private javax.swing.JButton btnMensualidades;
    private javax.swing.JButton btnPropietarios;
    private javax.swing.JButton btnViviendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenuItem mnuAlquileres;
    private javax.swing.JMenuItem mnuGanancias;
    private javax.swing.JMenuItem mnuInquilinos;
    private javax.swing.JMenuItem mnuMensualidades;
    private javax.swing.JMenuItem mnuPropietarios;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuViviendas;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
